---
words_to_merge:
  - ohne mwst
  - mit mwst
  - o. mwst
  - 0. mwst
  - mwst summe

# Market names roughly ordered by likelyhood.
# Can contain market locations for fuzzy parsing
markets:
  Colruyt:
     - colruyt
     - Colruyt
  Delhaize:
     - Delhaize
     - delhaize
  Penny:
     - penny
     - p e n n y
     - m a r k t gmbh
  REWE:
     - rewe
  Real:
     - real
  Kaufland:
    - kaufland
  Netto:
     - netto-online
  Rossmann:
    - rossmann
  DM:
    - dm-drogerie
  Kaiser's:
     - kaiser
     - kaiserswerther
  Aldi:
     - aldi
     - friedrichstr 128—133
  Lidl:
     - lidl
  Edeka:
    - edeka
  Drogerie:
     - drogerie
  Kodi:
     - kodi
  Tedi:
    - tedi
  Tankstelle:
#     - shell
#     - esso
     - aral
     - tankstelle
  IKEA:
    - ikea
  Migros:
     - genossenschaft migros
  Apotheke:
    - apotheke
  Parkhaus:
    - parkhaus
    - parken
  Galeria Karstadt Kaufhoff:
    - karstadt
  H&M:
    - h&m
  Bauhaus:
    - bauhaus
  Hornbach:
    - hornbach
  Hardeck:
    - hardeck

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - summe
  - zahlbetrag
  - gesamtbetrag
  - gesamt
  - kaufsumme
  - gesamtsumme
  - total
  - endbetrag
  - zahlen
#  - zwischensumme
  - betrag
  - sum
#  - bar
  - gegeben

brutto_keys:
  - brutoo
  - brutto-summe
  - bruttoumsatz
  - mit-mwst

netto_keys:
  - netto
  - nettobetrag
  - nettoumsatz
  - netto-entgelt
  - netto-warenwert
  - netto-summe
  - ohne-mwst
  - o.-mwst
  - 0.-mwst

steure_keys:
  - steuer
  - mwst
  - mwst-betrag
  - mwst-summe

paymentmethods:
  Cash:
    - bar
  EC:
    - girocard
    - lastschrift
    - ec


sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'

# Matches dates like 19.08.15 and 19. 08. 2015
#date_format: '(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{2}(\.\s?|[^a-zA-Z\d])(19|20)?\d\d)\s+)'
#date_format: '(?:\d{1,2}[-/th|st|nd|rd|dot\s]*)?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|d{1,2})?[a-z\s,.]*(?:\d{1,2}[-/th|st|nd|rd|dot)\s,]*)+(?:\d{2,4})+'
date_format: '(?:\d{1,4})[/\.-]\s?(?:\d{1,2})*(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|okt|0kt|juni|juli|mai)?[a-z\s,.]*[/\.-]\s?(?:\d{1,4})+'
date_format2: '(?:\d{1,4})[/\s/\.-]\s?(?:\d{1,2})*(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|okt|0kt|juni|juli|mai)*(?:january|februar|marz|april|mai|juni|juli|august|september|oktober|november|dezember)?[/\s/\.-]\s?(?:\d{1,4})+'


